apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes
spec:
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
        - name: probes
          image: probes:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: probes
spec:
  selector:
    app: probes
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
