apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes
spec:
  selector:
    matchLabels:
      app: probes
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
        - name: probes
          image: probes:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=75
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: probes
spec:
  selector:
    app: probes
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
